--- 
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata: 
  name: rabbitmq-operator
  namespace: edge-clusters
spec: 
  paths: 
    - rabbitmq-operator
  repo: "https://github.com/edge-orchestration/app-fleet-demo"
  branch: "0.2.1"
  targets: 
    - name: manufacturing-edge-clusters
      clusterSelector:
        matchLabels:
          industry: manufacturing
      