apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqserver
spec:
  replicas: 1
  persistence:
    storage: {{ .Values.rabbitmqServer.persistence.storage }}
    {{ if .Values.rabbitmqServer.persistence.storageClassName }}
    storageClassName: {{ .Values.rabbitmqServer.persistence.storageClassName | quote }}
    {{- end }}
  resources:
    requests:
      cpu: {{ .Values.rabbitmqServer.resources.requests.cpu }}
      memory: {{ .Values.rabbitmqServer.resources.requests.memory }}
    limits:
      cpu: {{ .Values.rabbitmqServer.resources.limits.cpu }}
      memory: {{ .Values.rabbitmqServer.resources.limits.memory }}
